apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.cromwell" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.cromwell" . | nindent 4 }}
data:
  {{ .Values.config.file }}: {{ include "cromwell.config" . | b64enc | quote }}
