{{- if and .Values.persistence.enabled .Values.persistence.internal}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvcName }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.cromwell" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvcSize }}
{{- end }}