---
apiVersion: v1
data:
  nginx.conf: |
    # Run as a less privileged user for security reasons.
    user nginx;
kind: ConfigMap
metadata:
  name: cm-ask
  annotations:
    reloader.stakater.com/match: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    reloader.stakater.com/search: "true"
spec:
  containers:
    - image: nginx:alpine
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /tmp/ak.txt
          name: ask
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: registry
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  volumes:
    - name: ask
      configMap:
        name: cm-ask
        items:
          - key: nginx.conf
            path: nginx.conf
        defaultMode: 420
