apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patches:
  - patch: |-
      - op: replace
        path: /apiserver-mysql.yaml/wes/endpoint
        value: http://180.184.43.200:8000
    target:
      kind: ConfigMap
      name: cm-apiserver

