image:
  repository: docker.io
  project: bioos
  web_name: web:v1.14
  apiserver_name: apiserver:v1.12
  pullPolicy: IfNotPresent

imagePullSecrets: []
replicaCount: 1
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

podAnnotations: {}
podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  web_port: 80
  api_http_port: 8888
  api_grpc_port: 50051

ingress:
  enabled: true
  className: ""
  annotations:
    {
      # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
      nginx.ingress.kubernetes.io/proxy-body-size: "64m",
    }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
          service_name: web
          service_port: 80

  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

notebook:
  images:
    - name: datascience
      version: "1.0"
      description: "this is official image"
      image: jupyter/datascience-notebook:hub-3.0.0
  resources:
    - cpu: 1
      memory: 1Gi
      disk: 20Gi
    - cpu: 2
      memory: 4Gi
      disk: 20Gi

mysql:
  hostname: mysql
  database: bioos
  username: root
  password: test

storage:
  pvc: bioos-storage-pvc
  mountPath: /app/conf/fs

wes:
#  cromwell service address
  endpoint: http://180.184.43.61:8000

jupyterhub:
#  jupyterhub service address
  endpoint: http://180.184.43.61/jupyterhub
  adminToken: c876b254956a433aaf02836605565af6
