image:
  repository: vecps.cargo.io
  project: bioos
  web_name: bioos_web:v1.1
  apiserver_name: bioos_apiserver:v1.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
replicaCount: 1
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

podAnnotations: {}
podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  mysql_port: 3306
  web_port: 80
  api_http_port: 8888
  api_grpc_port: 50051

ingress:
  enabled: true
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  database: bioos

storage:
  pvc: bioos-storage-pvc
  mountPath: /app/conf/fs

jupyterhub:
  endpoint: http://localhost/jupyterhub
  adminToken: sometoken

notebook:
  images:
    - name: sample
      version: '1.0'
      description: 'this is official sample image'
      image: jupyterhub/k8s-singleuser-sample:2.0.0
      updateTime: '2023-05-04T04:04:05Z'
  resources:
    - cpu: 1
      memory: 1Gi
      disk: 20Gi
    - cpu: 2
      memory: 4Gi
      disk: 20Gi
      gpu:
        model: 'Nvidia Tesla T4'
        memory: 64Gi
        card: 1
      nodeSelector: {}
