imagePullSecrets: []
hub:
  baseUrl: "/jupyterhub/"
  allowNamedServers: true
  config:
    NologinAuthenticator:
      username: nobody
    JupyterHub:
      admin_access: true
      authenticator_class: myauthenticator.NologinAuthenticator
      tornado_settings:
        slow_spawn_timeout: 0
        headers:
          Access-Control-Allow-Origin: "*"
          Content-Security-Policy: "frame-ancestors 'self' http://localhost"
    Spawner:
      args:
        - "--NotebookApp.allow_origin=*"
        - '--NotebookApp.tornado_settings={"headers":{"Content-Security-Policy": "frame-ancestors ''self'' http://localhost"}}'
  image:
    name: bioos/jupyterhub
    tag: "v1.0"
  networkPolicy:
    enabled: false
  db:
    type: mysql
    url: mysql+pymysql://root:test@mysql:3306/bioos

singleuser:
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
  image:
    name: jupyterhub/k8s-singleuser-sample
  storage:
    type: none
  cpu:
    limit: 1
    guarantee: 1
  memory:
    limit: 1G
    guarantee: 1G

scheduling:
  userScheduler:
    enabled: false
  userPlaceholder:
    enabled: false

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false
