{{- if .Values.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bioos-apiserver
  labels:
    {{- include "bioos.apiserver-lables" . | nindent 4 }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods", "persistentvolumeclaims", "secrets", "services", "endpoints"]
    verbs: ["get", "watch", "list", "create", "delete", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bioos-apiserver
  labels:
    {{- include "bioos.apiserver-lables" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bioos.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: bioos-apiserver
  apiGroup: rbac.authorization.k8s.io
{{- end }}
