apiVersion: v1
kind: Service
metadata:
  name: apiserver
  labels:
    {{- include "bioos.apiserver-lables" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api_http_port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.api_grpc_port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "bioos.apiserver-selectorLabels" . | nindent 4 }}
