apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "bioos.web-lables" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.web_port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "bioos.web-selectorLabels" . | nindent 4 }}
